# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [10]:
def check(numbers_x):
    if (numbers_x[0]== numbers_x[-1]):
        return True
    else: 
        return False
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]
print("Check if first list has same first and last numbers\n")
print(check(numbers_x))
print("Check if first list has same first and last numbers\n")
check(numbers_y)

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

Check if first list has same first and last numbers

True
Check if first list has same first and last numbers



False





# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [12]:
import numpy as np
a = np.array([1,2,3,7,8])
b = np.array([5,4,3,9,0])
# for addition
x=a+b 
print("The result of element wise addition is as follows:",x)
# for multiplication.
y = a*b
print("The result of element wise multiplication is as follows: ",y)

The result of element wise addition is as follows: [ 6  6  6 16  8]
The result of element wise multiplication is as follows:  [ 5  8  9 63  0]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [22]:
a = np.array([1,2,3,7,8,0,9,5,6,12,13,14])
# using reshape to create dimensions:
print("The reshaped array is as follows:",a.reshape(3,4))
# basically i created a scalar and multiplied it with array a
x = np.array([[1, 2, 3], [4, 5, 6]])
y =np.array([[4,5,6],[4,5,6]])
# for vertically
print("concatenating it using vertically")
c = np.concatenate((x,y), axis= 0)
print(c)
print("concatenating it using horizontally")
d = np.concatenate((x,y), axis= 1)
print(d)


The reshaped array is as follows: [[ 1  2  3  7]
 [ 8  0  9  5]
 [ 6 12 13 14]]
concatenating it using vertically
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
concatenating it using horizontally
[[1 2 3 4 5 6]
 [4 5 6 4 5 6]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [42]:
# Initialize an empty list called shopping_cart to store items.
shopping_cart=[]
# Display a welcome message and available products.
print("Welcome valuable customer we welcome you to our all get anime and manga store.(^.^)\n. What would you like to get?\n. We have:\n 1)_mashle magic and muscles(MMAM) manga all 3 volumes\n 2)_Demon Slayer(DS) all 8 volumes\n 3)_solo leveling(SL).\n 4)_case study of vanitas(CSV)\n ")
# now creating the dictionary which will be used.
a= {
    'MMAM': 1500,
    'DS': 3000,
    'SL': 4000,
    'CSV':9000
}
#  now we intend to make sure that the user can access the following amounts using the index values only.
print("Enter q to quit the program and enter y to continue shopping")
s = str(input("Enter the letter according to your choice:"))
while(s!='q'):
    x= int(input("Enter any one of the following using the numbers assigned to them wish you happy shopping."))
    value= list(a.values())[(x-1)]
    key = list(a)[(x-1)]
    print("---------- You have selected ",key," for  buying its price is: ",value," ----------\n")
    shopping_cart.append(key)
    shopping_cart.append(value)
    print("****The product has been added to the cart****")
    print("-----------------------------------------------")
    print("Enter q to quit the program and enter y to continue shopping")
    s = str(input("Enter the letter according to your choice:"))
print("------------------------------------------------")
print("You have the following list: ",shopping_cart)
print("Dear customer it was an amazing experience to work with you i hope to see you again soon (*.*), good bye")

Welcome valuable customer we welcome you to our all get anime and manga store.(^.^)
. What would you like to get?
. We have:
 1)_mashle magic and muscles(MMAM) manga all 3 volumes
 2)_Demon Slayer(DS) all 8 volumes
 3)_solo leveling(SL).
 4)_case study of vanitas(CSV)
 
Enter q to quit the program and enter y to continue shopping
Enter the letter according to your choice:y
Enter any one of the following using the numbers assigned to them wish you happy shopping.1
---------- You have selected  MMAM  for  buying its price is:  1500  ----------

****The product has been added to the cart****
-----------------------------------------------
Enter q to quit the program and enter y to continue shopping
Enter the letter according to your choice:y
Enter any one of the following using the numbers assigned to them wish you happy shopping.3
---------- You have selected  SL  for  buying its price is:  4000  ----------

****The product has been added to the cart****
---------------------------------

# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [49]:
def classify_emails(emails):
    # these are some keywords which are specifically in these emails 
    important_keys=["urgent", "important","remainder"]
    promotion_keys=["sale", "discount", "speacial"]
    spam_keys=["update", "verify", "confirm", "unable"]
    # these are the lists for the emails
    important_email=[]
    promotion_email=[]
    spam_email=[]
    for i in emails:
        if any(keyword in i.lower() for keyword in important_keys):
            important_email.append(i)
        elif any(keyword in i.lower() for keyword in promotion_keys):
            promotion_email.append(i)
        elif any(keyword in i.lower() for keyword in spam_keys):
            spam_email.append(i)
    return important_email,promotion_email,spam_email
        
            
# now the list of emails:
emails = ["Urgent! return to meeting the client wants a change in the product","Sale 25 % off on the specific book speacial offer on speacial occassions","Verify that its your account active on device XXX","Important remainder last day for assignment", " Heavy Discount on the course just for you ","Verify your new number and update your information on your google account"]
important_email,promotion_email,spam_email =classify_emails(emails)
print(". The important emails are:",important_email,"\n" )
print(". The promotion emails are:",promotion_email,"\n" )
print(". The spam emails are:",spam_email,"\n" )



. The important emails are: ['Urgent! return to meeting the client wants a change in the product', 'Important remainder last day for assignment'] 

. The promotion emails are: ['Sale 25 % off on the specific book speacial offer on speacial occassions', ' Heavy Discount on the course just for you '] 

. The spam emails are: ['Verify that its your account active on device XXX', 'Verify your new number and update your information on your google account'] 



# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [60]:
dictionary= {"hello": "ola", "friends":"amigos", "thank you": "gracias", "mister": "senior", "delicous":"delicioso","I am":"soi"}
print("Enter e to quit the program and enter y to continue looking")
s = str(input("Enter the letter according to your choice:"))
print("-----------------------------------------------")
a = str(input(". Enter any English word of your choice:\n "))
while(s!='e'):
    if (a in dictionary):
        print("***The Spanish translation for this ",a ," is: ", dictionary[a],"***")
        print("-----------------------------------------------")

    elif (a not in  dictionary):
        print("***The translation for this word is not available do try again later.***")
    print("Enter e to quit the program and enter y to continue shopping")
    s = str(input("Enter the letter according to your choice:"))
        

    
            

Enter e to quit the program and enter y to continue looking
Enter the letter according to your choice:y
-----------------------------------------------
. Enter any English word of your choice:
 hello
***The Spanish translation for this  hello  is:  ola ***
-----------------------------------------------
Enter q to quit the program and enter y to continue shopping
Enter the letter according to your choice:e


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [61]:
import pandas as pd
url ="https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(url,sep= ",", encoding = "utf-8")
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [62]:
some = df["Global_Sales"].sum()
some

8920.44

In [64]:
highest = df["Global_Sales"].max()
highest

82.74

In [65]:
NA = df["NA_Sales"].mean()
NA

0.26466742981082064

In [68]:
EU = df["EU_Sales"].mean()
EU

0.14665200626581515

In [67]:
JP = df["JP_Sales"].mean()
JP

0.077781660441017

In [66]:
others= df["Other_Sales"].mean()
others

0.0480630196409206

In [73]:
df.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [75]:
NA = df["NA_Sales"].sum()
print(NA)
EU = df["EU_Sales"].sum()
print(EU)
JP = df["JP_Sales"].sum()
print(JP)

4392.950000000001
2434.1299999999997
1291.0200000000002


In [74]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [76]:
df.head(10)

Rank                       Name Platform    Year         Genre Publisher  \
0     1                 Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2          Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3             Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4          Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5   Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   
5     6                     Tetris       GB  1989.0        Puzzle  Nintendo   
6     7      New Super Mario Bros.       DS  2006.0      Platform  Nintendo   
7     8                   Wii Play      Wii  2006.0          Misc  Nintendo   
8     9  New Super Mario Bros. Wii      Wii  2009.0      Platform  Nintendo   
9    10                  Duck Hunt      NES  1984.0       Shooter  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37  
5     23.20      2.26      4.22         0.58         30.26  
6     11.38      9.23      6.50         2.90         30.01  
7     14.03      9.20      2.93         2.85         29.02  
8     14.59      7.06      4.70         2.26         28.62  
9     26.93      0.63      0.28         0.47         28.31

In [ ]:
global_sales= groupby()